version: "3.8"
services:
  mtm_guardian:
    image: fmguardia/mtm-guardian:0.3
    deploy:
      mode: global
      restart_policy:
        condition: any
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log:ro
      - /:/hostfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    environment:
      - API_ENDPOINT=http://170.205.37.204:8081
      - DOCKER_INTERVAL=10
      - VM_INTERVAL=20
      - MANAGE_FIREWALL=false
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_ETC=/hostfs/etc
    # Mantendo network_mode: host para coleta de métricas do sistema
    network_mode: host
    # Adicionando privilégios para acessar os processos do host
    privileged: true
    pid: host
